# Generated by Django 6.0.7 on 2026-07-30 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=30, unique=True)),
                ('language', models.CharField(default='English', max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('pdf_filename', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('position', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='bible.book')),
            ],
            options={
                'ordering': ['book__position', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.chapter')),
            ],
            options={
                'ordering': ['chapter', 'number'],
            },
        ),
        migrations.CreateModel(
            name='VerseText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('bible_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_texts', to='bible.bibleversion')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bible.verse')),
            ],
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('book', 'number'), name='unique_chapter_per_book'),
        ),
        migrations.AddConstraint(
            model_name='verse',
            constraint=models.UniqueConstraint(fields=('chapter', 'number'), name='unique_verse_per_chapter'),
        ),
        migrations.AddIndex(
            model_name='versetext',
            index=models.Index(fields=['bible_version', 'verse'], name='bible_verse_bible_v_6acc46_idx'),
        ),
        migrations.AddConstraint(
            model_name='versetext',
            constraint=models.UniqueConstraint(fields=('bible_version', 'verse'), name='unique_text_per_version_and_verse'),
        ),
    ]
