# Generated by Django 6.0.7 on 2026-08-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProperName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PERSON', 'Person'), ('PLACE', 'Place'), ('OTHER', 'Other')], db_index=True, max_length=10)),
                ('entry_key', models.CharField(max_length=300, unique=True)),
                ('display_name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('entry_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('briefest', models.TextField(blank=True)),
                ('brief', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('article', models.TextField(blank=True)),
                ('all_names', models.TextField(blank=True)),
                ('strong_numbers', models.TextField(blank=True)),
                ('references', models.JSONField(blank=True, default=list)),
                ('forms', models.JSONField(blank=True, default=list)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['display_name', 'entry_key'],
                'indexes': [models.Index(fields=['category', 'display_name'], name='proper_name_category_name')],
            },
        ),
    ]
