# Generated by Django 6.0.7 on 2026-08-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_propername'),
    ]

    operations = [
        migrations.CreateModel(
            name='TamilDictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100, unique=True)),
                ('definition', models.TextField()),
            ],
            options={
                'verbose_name': 'Tamil dictionary entry',
                'verbose_name_plural': 'Tamil dictionary entries',
                'ordering': ['word'],
            },
        ),
    ]
